FROM openjdk:10-jre

RUN apt-get update
RUN apt-get install -y procps
RUN apt-get install -y python3 python3-pip
RUN pip3 install requests==2.18.4
WORKDIR /azkaban
ADD azkaban-web-server/build/install/azkaban-web-server /azkaban
ADD common /azkaban
ADD scripts /scripts
RUN chmod +x /scripts/*

ENV AZKABAN_OPTS -Xmx16G -Xms16G -XX:+ParallelRefProcEnabled
EXPOSE 8081

CMD /scripts/start-web.sh
