FROM openjdk:11.0.8-jre

RUN apt-get update
RUN apt-get install -y procps
RUN apt-get install -y python3 python3-pip
RUN pip3 install requests==2.18.4
WORKDIR /azkaban
ADD azkaban-exec-server/build/install/azkaban-exec-server /azkaban
ADD common /azkaban
ADD scripts /scripts
RUN chmod +x /scripts/*
ADD yaml /yaml

ENV AZKABAN_OPTS -Xmx4G -Xms4G -XX:+ParallelRefProcEnabled
EXPOSE 12321

CMD /scripts/start-exec.sh
