FROM openjdk:8-jre-stretch

RUN apt-get update
RUN apt-get install -y procps
RUN apt-get install -y python3 python3-pip
RUN pip3 install requests==2.18.4
WORKDIR /azkaban-exec-server
ADD azkaban-exec-server/build/install/azkaban-exec-server /azkaban-exec-server
ADD common /azkaban-exec-server
ADD common /common
ADD scripts /scripts
RUN chmod +x /scripts/*
ADD yaml /yaml

ENV AZKABAN_OPTS -Xmx8G -Xms8G -XX:+ParallelRefProcEnabled 
EXPOSE 12321

CMD /scripts/start-exec.sh
