FROM java:8-jre

RUN rm /etc/apt/sources.list.d/jessie-backports.list
RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-pip
WORKDIR /azkaban-web-server
ADD azkaban-web-server/build/install/azkaban-web-server /azkaban-web-server
ADD common /azkaban-web-server
ADD scripts /scripts
RUN chmod +x /scripts/*

ENV AZKABAN_OPTS -Xmx8G -Xms8G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled \
                 -XX:-ResizePLAB -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1HeapWastePercent=20 \
                 -XX:InitiatingHeapOccupancyPercent=75
EXPOSE 8081

CMD /scripts/start-web.sh
