# From: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/198.0.0/debian_slim/Dockerfile
# Changing jessie to stretch and adding gnupg2
#######################################################################################
FROM debian:stretch
RUN apt-get update && apt-get install -y gnupg2

ENV CLOUD_SDK_VERSION 198.0.0

ARG INSTALL_COMPONENTS
RUN apt-get update -qqy && apt-get install -qqy \
        curl \
        gcc \
        python-dev \
        python-setuptools \
        apt-transport-https \
        lsb-release \
        openssh-client \
        git \
    && easy_install -U pip && \
    pip install -U crcmod && \
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && apt-get install -y google-cloud-sdk=${CLOUD_SDK_VERSION}-0 $INSTALL_COMPONENTS && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version
#######################################################################################

WORKDIR /scripts
ADD common /common
ADD scripts /scripts
RUN chmod +x /scripts/*
RUN apt-get update
RUN apt-get install -y python-dev default-libmysqlclient-dev kubectl
RUN pip install requests mysqlclient

CMD /scripts/sync_exec.py
