FROM openjdk:8-jre-stretch

RUN apt-get update
RUN apt-get install -y procps
RUN apt-get install -y python3 python3-pip
RUN pip3 install requests==2.18.4
WORKDIR /azkaban-web-server
ADD azkaban-web-server/build/install/azkaban-web-server /azkaban-web-server
ADD common /azkaban-web-server
ADD common /common
ADD scripts /scripts
RUN chmod +x /scripts/*

ENV AZKABAN_OPTS -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled \
                 -XX:-ResizePLAB -XX:ParallelGCThreads=6 -XX:ConcGCThreads=6 -XX:G1HeapWastePercent=20 \
                 -XX:InitiatingHeapOccupancyPercent=75
EXPOSE 8081

CMD /scripts/start-web.sh
