apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: exec
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exec
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
