apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/[project-id]/azkaban-web:[image-tag]
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "20G"
            cpu: "6000m"
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/scripts/shutdown-web.sh"]
        volumeMounts:
          - name: tmp-pod
            mountPath: /tmp/pod
      - name: sync
        image: gcr.io/[project-id]/azkaban-sync:[image-tag]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=[project-id]:asia-east1:azkaban-mysql-db=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: tmp-pod
            mountPath: /tmp/pod
            readOnly: true
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
        livenessProbe:
          failureThreshold: 5
          exec:
            command: ["nc", "-z", "127.0.0.1", "3306"]
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          exec:
            command: ["nc", "-z", "127.0.0.1", "3306"]
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "while true; do if [ -f /tmp/pod/main-terminated ]; then exit 0; fi; sleep 1; done"]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: tmp-pod
          emptyDir: {}

